FROM apache/airflow:2.10.3
USER root
RUN apt-get update && apt-get install -y cmake
USER airflow
COPY requirements.txt /
RUN pip install --no-cache-dir "apache-airflow==${AIRFLOW_VERSION}" -r /requirements.txt